name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
assignees:
  - sneat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Give us the details of the steps taken, and the unexpected result you experienced.
      placeholder: |
        Reproduction steps:
        1. I clicked the token.
        2. The token jumped across the scene 10 spaces to the left.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is the expected behaviour?
      description: If this is a bug, what would you expect the fix to do?
      placeholder: |
        When I click the token, it becomes selected and stays in its current position.
  - type: textarea
    id: logs
    attributes:
      label: Relevant Errors and Warnings
      description: Is there an error message or warning in the browser console when you experienced this behaviour? Right after triggering the bug, press F12 and copy anything relevant in the console window. Paste that here.
      render: shell
  - type: textarea
    id: debug
    attributes:
      label: Additional Support Details
      description: With your Foundry VTT game active, you may click the Game Settings tab, then click the Support button. Please copy the debug information and paste it below.
      placeholder: |
        Foundry Virtual Tabletop: Version 13, 13.345
        Game System: ose, 2.1.0
        Active Modules: 9
        Performance Mode: 1

        OS: Intel Mac OS X 10.15
        Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
        GPU: Apple M1
        Max Texture Size: 8192
        ...
  - type: input
    id: core-version
    attributes:
      label: Foundry VTT Core Version
      description: Which version of Foundry VTT is installed? Skip this if you provided Additional Support Details.
      placeholder: v13.345
  - type: input
    id: system-version
    attributes:
      label: Old-School Essentials Core Version
      description: Which version of Old-School Essentials Foundry VTT Edition are you using? Skip this if you provided Additional Support Details.
